# Generated by Django 3.1.5 on 2021-02-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200219_1614'),
        ('certificate', '0002_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
