# Generated by Django 2.2 on 2021-02-05 03:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_auto_20210204_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='name',
            new_name='name_certi',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='id',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='url_key',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
