# Generated by Django 2.2 on 2021-02-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_auto_20210205_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='name_certi',
            new_name='name',
        ),
    ]
